name: Update pkg.go.dev

on:
  push:
    tags:
      - '*'

jobs:
  update-pkg-go-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Update pkg.go.dev
        run: |
          ESCAPED_MODULE=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
          curl https://proxy.golang.org/github.com/$ESCAPED_MODULE/@v/$GITHUB_REF_NAME.info
